### ISSUE TITLE
SDIO兼容问题

### ISSUE THREAD

**Issue by ZGCloud-ZGY** [Synwit-Co-Ltd/SWM341_Lib#2]
目前使用芯天下的XTSDG01GWSIG这款SD Nand，调用SDIO_Init初始化时报了SD_RES_ERR。发现是SWM341_sdio.c:82行的问题，这款SD Nand获取到的resp值是0x20，导致初始化失败，屏蔽后初始化正常，文件读写也正常。这里能否优化判断？

**Comment by XIVN1987** [comment]
已修正，感谢反馈。。
