### ISSUE TITLE
Could you add CMake build support?

### ISSUE THREAD

**Issue by ccldmf** [Synwit-Co-Ltd/SWM341_Lib#5]
Currently, projects seems to be build with keil or other IDE, with not support for CMake. Could you please add CMake support to make it have better platform portability?

**Comment by XIVN1987** [comment]
GCC support: [https://github.com/Synwit-Co-Ltd/Synwit.SWM32_GCC](https://github.com/Synwit-Co-Ltd/Synwit.SWM32_GCC)

**Comment by ccldmf** [comment]
OK, thanks!

**Comment by ccldmf** [comment]
I have successfully build the sample code on linux, but how to use JLink download the binary file to the device? And try to use JLink debug the device on linux,  start GDB server: "JLinkGDBServerCLExe -device CORTEX-M33 -if SWD -speed 4000 -port 4242 -LocalhostOnly", but "target remote :4242", it will be failed, like this:
 "(gdb) target remote :4242
Remote debugging using :4242
__muldf3 () at ../../../../../../libgcc/config/arm/ieee754-df.S:850
../../../../../../libgcc/config/arm/ieee754-df.S: No such file or directory.
"
How to fix this issue? Thanks!

**Comment by XIVN1987** [comment]
for download, you can use JFlash or SWMProg
https://github.com/Synwit-Co-Ltd/JFlash
https://github.com/Synwit-Co-Ltd/SWMProg

**Comment by XIVN1987** [comment]
for debug, you can use J-Link GDB Server and VSCode with Cortex-Debug plugin.
launch configuration: https://github.com/Synwit-Co-Ltd/micropython/blob/master/upy34s.code-workspace
